### ISSUE TITLE
openresty-1.11.2.2 proxy_pass return `empty reply from server`

### ISSUE THREAD

**Issue by linsir** [openresty/openresty#240]
Hello, I have a  Raspberry Pi 2 (raspbain 8). and I try install OpenResty 1.11.2.2 use reverse proxy the web app that listen at 127.0.0.1:5000. But I use curl to test it ,and return `empty reply from server`

    root@linsirpi:~/openresty#uname -a
    Linux linsirpi 4.4.34-v7+ #930 SMP Wed Nov 23 15:20:41 GMT 2016 armv7l GNU/Linux

this my config:

```
server {
        listen 80;
	server_name httpbin.org; 
    	root /home/www/;
    	index app.py index.html;
        # Allow file uploads
        client_max_body_size 50M;
 
        location ~ / {
            proxy_pass_header Server;
            proxy_set_header Host $http_host;
            proxy_redirect off;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Scheme $scheme;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass http://127.0.0.1:5000;
        }
        access_log /var/log/nginx/httpbin.org.log;
}
```
and I try to compile nginx-1.11.10 and it works, any ideas ?

**Comment by detailyang** [comment]
Hello.

Will you carefully check the other error ? Or Will you provide more detail to  reproduce the  error. We cannot help you much more if you cannot provide the way to reproduce  error :(

**Comment by linsir** [comment]
Thanks for reply so quickly. This is the log of web app. 

```
127.0.0.1 - - [16/Mar/2017 17:06:25] "GET / HTTP/1.0" 200 -
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 42624)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 657, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 716, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
```
I try to search by Google ,but something were found to be related to it.

**Comment by detailyang** [comment]
@linsir Can you provide the nginx error log (I guess nginx was core dump).

**Comment by linsir** [comment]
I set log level to `debug` , get this:

```
2017/03/16 17:04:18 [notice] 23587#0: signal 17 (SIGCHLD) received
2017/03/16 17:04:18 [alert] 23587#0: worker process 23588 exited on signal 11
2017/03/16 17:04:18 [notice] 23587#0: start worker process 23591
```
have no more.

**Comment by detailyang** [comment]
Yup, nginx was coredump.  You should enable coredumpe by as the following in nginx.conf:

```bash
worker_rlimit_core  10G;
working_directory   /path/to/cores/ #make sure worker can write this dir;
```

**Comment by linsir** [comment]
@detailyang Hello, I set this:

```
worker_rlimit_core  10G;
working_directory   /tmp;
```
but I can not get any file at `/tmp/cores`

**Comment by detailyang** [comment]
Consider it resolved. More detail at [https://trac.nginx.org/nginx/ticket/912](https://trac.nginx.org/nginx/ticket/912)

**Comment by linsir** [comment]
Thanks @detailyang to find out about it.

**Comment by linsir** [comment]
Just add `--with-cc-opt=-fno-optimize-sibling-calls` and it works.
