### ISSUE TITLE
Crash on FreeBSD 10.3 amd64

### ISSUE THREAD

**Issue by sparvu** [openresty/openresty#296]
We have noticed that NGINX (OpenResty latest) crashes with a core dump on FreeBSD 10.3 amd64, physical server based on a AMD cpu. This has happened after OpenResty 1.11.2.2 (this was running ok). This does not happen on a VM or other physical x64 server installation. 

The only solution on this hardware server (again this is a physical server, no virtualization, the FreeBSD 10.3 is installed on bare metal) is to downgrade to OpenResty 1.11.2.2 which is working fine.  

## Crash

```
# ./nginx -V
Illegal instruction (core dumped)
```

```
# gdb ./nginx nginx.core 
GNU gdb 6.1.1 [FreeBSD]
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "amd64-marcel-freebsd"...
Core was generated by `nginx'.
Program terminated with signal 4, Illegal instruction.
Reading symbols from /lib/libcrypt.so.5...done.
Loaded symbols for /lib/libcrypt.so.5
Reading symbols from /lib/libm.so.5...done.
Loaded symbols for /lib/libm.so.5
Reading symbols from /usr/local/lib/libpcre.so.1...done.
Loaded symbols for /usr/local/lib/libpcre.so.1
Reading symbols from /usr/lib/libssl.so.7...done.
Loaded symbols for /usr/lib/libssl.so.7
Reading symbols from /lib/libcrypto.so.7...done.
Loaded symbols for /lib/libcrypto.so.7
Reading symbols from /lib/libz.so.6...done.
Loaded symbols for /lib/libz.so.6
Reading symbols from /lib/libgcc_s.so.1...done.
Loaded symbols for /lib/libgcc_s.so.1
Reading symbols from /lib/libc.so.7...done.
Loaded symbols for /lib/libc.so.7
Reading symbols from /lib/libthr.so.3...done.
Loaded symbols for /lib/libthr.so.3
Reading symbols from /libexec/ld-elf.so.1...done.
Loaded symbols for /libexec/ld-elf.so.1
#0  0x00000000004ed70b in x64_init_random_constructor () at lj_str_hash_x64.h:184
184	lj_str_hash_x64.h: No such file or directory.
	in lj_str_hash_x64.h

(gdb) bt
#0  0x00000000004ed70b in x64_init_random_constructor () at lj_str_hash_x64.h:184
#1  0x0000000000553272 in __do_global_ctors_aux ()
#2  0x000000000041c376 in _init ()
#3  0x00007fffffffe080 in ?? ()
#4  0x0000000800799a9f in r_debug_state () from /libexec/ld-elf.so.1
#5  0x00000008007990ee in __tls_get_addr () from /libexec/ld-elf.so.1
#6  0x0000000800797439 in .text () from /libexec/ld-elf.so.1
#7  0x0000000000000000 in ?? ()
Current language:  auto; currently minimal

(gdb) bt full
#0  0x00000000004ed70b in x64_init_random_constructor () at lj_str_hash_x64.h:184
No locals.
#1  0x0000000000553272 in __do_global_ctors_aux ()
No symbol table info available.
#2  0x000000000041c376 in _init ()
No symbol table info available.
#3  0x00007fffffffe080 in ?? ()
No symbol table info available.
#4  0x0000000800799a9f in r_debug_state () from /libexec/ld-elf.so.1
No symbol table info available.
#5  0x00000008007990ee in __tls_get_addr () from /libexec/ld-elf.so.1
No symbol table info available.
#6  0x0000000800797439 in .text () from /libexec/ld-elf.so.1
No symbol table info available.
#7  0x0000000000000000 in ?? ()
No symbol table info available.

(gdb) info registers
rax            0xab4	2740
rbx            0x0	0
rcx            0x801c3083a	34389297210
rdx            0x178bfbff	395049983
rsi            0x7fffffffe508	140737488348424
rdi            0x802806400	34401707008
rbp            0x7fffffffdc00	0x7fffffffdc00
rsp            0x7fffffffdbd0	0x7fffffffdbd0
r8             0x0	0
r9             0xfffff80076a47000	-8794102534144
r10            0x41c368	4309864
r11            0x202	514
r12            0x8009b2660	34369906272
r13            0x0	0
r14            0x8007b6001	34367823873
r15            0x8007b4700	34367817472
rip            0x4ed70b	0x4ed70b <x64_init_random_constructor+11>
eflags         0x10246	66118
cs             0x43	67
ss             0x3b	59
ds             0x0	0
es             0x0	0
fs             0x0	0
gs             0x0	0


```

### Hardware
```
Copyright (c) 1992-2016 The FreeBSD Project.
Copyright (c) 1979, 1980, 1983, 1986, 1988, 1989, 1991, 1992, 1993, 1994
        The Regents of the University of California. All rights reserved.
FreeBSD is a registered trademark of The FreeBSD Foundation.
FreeBSD 10.3-RELEASE-p20 #0: Wed Jul 12 03:13:07 UTC 2017
    root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC amd64
FreeBSD clang version 3.4.1 (tags/RELEASE_34/dot1-final 208032) 20140512
CPU: AMD Athlon(tm) II X3 445 Processor (3100.07-MHz K8-class CPU)
  Origin="AuthenticAMD"  Id=0x100f53  Family=0x10  Model=0x5  Stepping=3
  Features=0x178bfbff<FPU,VME,DE,PSE,TSC,MSR,PAE,MCE,CX8,APIC,SEP,MTRR,PGE,MCA,CMOV,PAT,PSE36,CLFLUSH,MMX,FXSR,SSE,SSE2,HTT>
  Features2=0x802009<SSE3,MON,CX16,POPCNT>
  AMD Features=0xee500800<SYSCALL,NX,MMX+,FFXSR,Page1GB,RDTSCP,LM,3DNow!+,3DNow!>
  AMD Features2=0x37ff<LAHF,CMP,SVM,ExtAPIC,CR8,ABM,SSE4A,MAS,Prefetch,OSVW,IBS,SKINIT,WDT>
  SVM: NP,NRIP,NAsids=64
  TSC: P-state invariant
real memory  = 17179869184 (16384 MB)
avail memory = 16595103744 (15826 MB)
Event timer "LAPIC" quality 400
ACPI APIC Table: <021611 APIC1341>
FreeBSD/SMP: Multiprocessor System Detected: 3 CPUs
FreeBSD/SMP: 1 package(s) x 3 core(s)
 cpu0 (BSP): APIC ID:  0
 cpu1 (AP): APIC ID:  1
 cpu2 (AP): APIC ID:  2
random: <Software, Yarrow> initialized
Security policy loaded: TrustedBSD MAC/portacl (mac_portacl)
ioapic0 <Version 1.1> irqs 0-23 on motherboard
kbd1 at kbdmux0
acpi0: <ACRSYS ACRPRDCT> on motherboard
acpi0: Power Button (fixed)
cpu0: <ACPI CPU> on acpi0
cpu1: <ACPI CPU> on acpi0
cpu2: <ACPI CPU> on acpi0
hpet0: <High Precision Event Timer> iomem 0xfed00000-0xfed00fff irq 2,8 on acpi0
Timecounter "HPET" frequency 25000000 Hz quality 950
attimer0: <AT timer> port 0x40-0x43 on acpi0
Timecounter "i8254" frequency 1193182 Hz quality 0
Event timer "i8254" frequency 1193182 Hz quality 100
atrtc0: <AT realtime clock> port 0x70-0x71 on acpi0
Event timer "RTC" frequency 32768 Hz quality 0
Timecounter "ACPI-fast" frequency 3579545 Hz quality 900
acpi_timer0: <24-bit timer at 3.579545MHz> port 0x4008-0x400b on acpi0
pcib0: <ACPI Host-PCI bridge> port 0xcf8-0xcff on acpi0
pci0: <ACPI PCI bus> on pcib0
pci0: <memory, RAM> at device 0.0 (no driver attached)
isab0: <PCI-ISA bridge> port 0x4f00-0x4fff at device 1.0 on pci0
isa0: <ISA bus> on isab0
pci0: <memory, RAM> at device 1.2 (no driver attached)
pci0: <processor> at device 1.3 (no driver attached)
pci0: <memory, RAM> at device 1.4 (no driver attached)
ohci0: <OHCI (generic) USB controller> mem 0xfce7f000-0xfce7ffff irq 22 at device 2.0 on pci0
usbus0 on ohci0
ehci0: <EHCI (generic) USB 2.0 controller> mem 0xfce7ec00-0xfce7ecff irq 23 at device 2.1 on pci0
usbus1: EHCI version 1.0
usbus1 on ehci0
ohci1: <OHCI (generic) USB controller> mem 0xfce7d000-0xfce7dfff irq 20 at device 4.0 on pci0
usbus2 on ohci1
ehci1: <EHCI (generic) USB 2.0 controller> mem 0xfce7e800-0xfce7e8ff irq 21 at device 4.1 on pci0
usbus3: EHCI version 1.0
usbus3 on ehci1
hdac0: <NVIDIA MCP78 HDA Controller> mem 0xfce78000-0xfce7bfff irq 22 at device 7.0 on pci0
pcib1: <ACPI PCI-PCI bridge> at device 8.0 on pci0
pci1: <ACPI PCI bus> on pcib1
ahci0: <NVIDIA MCP77 AHCI SATA controller> port 0xd480-0xd487,0xd400-0xd403,0xd080-0xd087,0xd000-0xd003,0xcc00-0xcc0f mem 0xfce76000-0xfce77fff irq 23 at device 9.0 on pci0
ahci0: AHCI v1.20 with 6 3Gbps ports, Port Multiplier supported
ahci0: quirks=0x200<NOAA>
ahcich0: <AHCI channel> at channel 0 on ahci0
ahcich1: <AHCI channel> at channel 1 on ahci0
ahcich2: <AHCI channel> at channel 2 on ahci0
ahcich3: <AHCI channel> at channel 3 on ahci0
ahcich4: <AHCI channel> at channel 4 on ahci0
ahcich5: <AHCI channel> at channel 5 on ahci0
nfe0: <NVIDIA nForce MCP77 Networking Adapter> port 0xc880-0xc887 mem 0xfce7c000-0xfce7cfff,0xfce7e400-0xfce7e4ff,0xfce7e000-0xfce7e00f irq 20 at device 10.0 on pci0
miibus0: <MII bus> on nfe0
rgephy0: <RTL8169S/8110S/8211 1000BASE-T media interface> PHY 1 on miibus0
rgephy0:  none, 10baseT, 10baseT-FDX, 10baseT-FDX-flow, 100baseTX, 100baseTX-FDX, 100baseTX-FDX-flow, 1000baseT, 1000baseT-master, 1000baseT-FDX, 1000baseT-FDX-master, 1000baseT-FDX-flow, 1000baseT-FDX-flow-master, auto, auto-flow
nfe0: Using defaults for TSO: 65518/35/2048
nfe0: Ethernet address: f8:0f:41:1f:b2:89
pcib2: <ACPI PCI-PCI bridge> irq 16 at device 16.0 on pci0
pci2: <ACPI PCI bus> on pcib2
vgapci0: <VGA-compatible display> port 0xec00-0xec7f mem 0xfd000000-0xfdffffff,0xf0000000-0xf7ffffff,0xfa000000-0xfbffffff irq 16 at device 0.0 on pci2
vgapci0: Boot video device
hdac1: <NVIDIA GT108 HDA Controller> mem 0xfcf7c000-0xfcf7ffff irq 19 at device 0.1 on pci2
pcib3: <ACPI PCI-PCI bridge> irq 17 at device 18.0 on pci0
pci3: <ACPI PCI bus> on pcib3
pcib4: <ACPI PCI-PCI bridge> irq 18 at device 19.0 on pci0
pci4: <ACPI PCI bus> on pcib4
acpi_button0: <Power Button> on acpi0
sc0: <System console> at flags 0x100 on isa0
sc0: VGA <16 virtual consoles, flags=0x300>
vga0: <Generic ISA VGA> at port 0x3c0-0x3df iomem 0xa0000-0xbffff on isa0
atkbdc0: <Keyboard controller (i8042)> at port 0x60,0x64 on isa0
atkbd0: <AT Keyboard> irq 1 on atkbdc0
kbd0 at atkbd0
atkbd0: [GIANT-LOCKED]
ppc0: cannot reserve I/O port range
hwpstate0: <Cool`n'Quiet 2.0> on cpu0
ZFS filesystem version: 5
ZFS storage pool version: features support (5000)
Timecounters tick every 1.000 msec
hdacc0: <Realtek ALC888 HDA CODEC> at cad 0 on hdac0
hdaa0: <Realtek ALC888 Audio Function Group> at nid 1 on hdacc0
pcm0: <Realtek ALC888 (Analog 5.1+HP/2.0)> at nid 20,22,21,27 and 24,25,26 on hdaa0
```

### OpenResty 1.11.2.4 
Same crash patter happens as well with latest 1.11.2.5 

### FreeBSD 10.3 amd64
```
FreeBSD kronometrix 10.3-RELEASE-p20 FreeBSD 10.3-RELEASE-p20 #0: Wed Jul 12 03:13:07 UTC 2017     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
```

**Comment by agentzh** [comment]
@sparvu It seems that that metal box lacks SSE 4.2 instruction support and you deploy an OpenResty 1.11.2.5 binary compiled on a box *wth* SSE 4.2. You should compile OpenResty 1.11.2.5 on that metal directly so that the build system can detect the lack of SSE 4.2. (BTW, the SSE 4.2 detection test in OpenResty versions older than 1.11.2.5 is buggy, you need at least 1.11.2.5).

**Comment by sparvu** [comment]
@agentzh thanks a lot for clarifications. Unfortunately we cannot build OpenResty on this hdw since this is a production server used by one of our customers. 

I believe there is no way to disable via configure SSE4.2, if needed. Right ? So basically a simple requirement would be to have hardware which supports SSE4.2 instruction set. SSE4.2 instruction set is used within OpenResty for speed up string parsing or what ?

**Comment by agentzh** [comment]
@sparvu The SSE 4.2 CRC instruction is used for mitigating LuaJIT's string table hash collision risks. So it also has important security implications. That's why you should prepare special binaries for those without SSE 4.2 support instead of disabling SSE 4.2 for every boxes. It goes way beyond normal optimizations.

**Comment by sparvu** [comment]
@agentzh Righty. Good. I will advice our CU to upgrade and use more modern CPU architectures with support for SSE 4.2. Thanks again for quick answer.

**Comment by agentzh** [comment]
@sparvu BTW, you can try the ./configure option --with-luajit-xcflags='-mno-sse4.2' to disable SSE 4.2 in a box with SSE 4.2 support. That can help you "cross-compile".
