### ISSUE TITLE
ra_rematk() in lj_asm.c

### ISSUE THREAD

**Issue by hongxiaolong** [openresty/openresty#378]
I found the function ra_rematk() in lj_asm.c version as follows:

```
openresty-1.13.6.2/bundle/LuaJIT-2.1-20180420/src/lj_asm.c

/* Rematerialize constants. */
static Reg ra_rematk(ASMState *as, IRRef ref)
{
  IRIns *ir;
  Reg r;
  if (ra_iskref(ref)) {
    r = ra_krefreg(ref);
    lua_assert(!rset_test(as->freeset, r));
    ra_free(as, r);
    ra_modified(as, r);
#if LJ_64
    emit_loadu64(as, r, ra_krefk(as, ref));
#else
    emit_loadi(as, r, ra_krefk(as, ref));
#endif
    return r;
  }
  ir = IR(ref);
  r = ir->r;
  lua_assert(ra_hasreg(r) && !ra_hasspill(ir->s));
  ra_free(as, r);
  ra_modified(as, r);
  ir->r = RID_INIT;  /* Do not keep any hint. */
  RA_DBGX((as, "remat     $i $r", ir, r));
#if !LJ_SOFTFP32
  if (ir->o == IR_KNUM) {
    emit_loadk64(as, r, ir);
```

Pay attention to the last line, I can not found how the line was patched from the patch file luajit-2.0.0-2ad9834d.patch, differing from OpenResty luajit2 fork or officia luajit:

```
/* Rematerialize constants. */
static Reg ra_rematk(ASMState *as, IRRef ref)
{
  IRIns *ir;
  Reg r;
  if (ra_iskref(ref)) {
    r = ra_krefreg(ref);
    lua_assert(!rset_test(as->freeset, r));
    ra_free(as, r);
    ra_modified(as, r);
    emit_loadi(as, r, ra_krefk(as, ref));
    return r;
  }
  ir = IR(ref);
  r = ir->r;
  lua_assert(ra_hasreg(r) && !ra_hasspill(ir->s));
  ra_free(as, r);
  ra_modified(as, r);
  ir->r = RID_INIT;  /* Do not keep any hint. */
  RA_DBGX((as, "remat     $i $r", ir, r));
#if !LJ_SOFTFP
  if (ir->o == IR_KNUM) {
    emit_loadn(as, r, ir_knum(ir));
``` 

----

And I run into a coredump as follows:

```
#0  0x00000038a9c328a5 in raise () from /lib64/libc.so.6
#1  0x00000038a9c34085 in abort () from /lib64/libc.so.6
#2  0x00000038a9c2ba1e in __assert_fail_base () from /lib64/libc.so.6
#3  0x00000038a9c2bae0 in __assert_fail () from /lib64/libc.so.6
#4  0x00000000006c383d in ptr2addr (p=<value optimized out>) at lj_emit_x86.h:95
#5  0x00000000006c43ff in emit_rma (as=<value optimized out>, xo=XO_MOVSD, rr=22, addr=<value optimized out>) at lj_emit_x86.h:353
#6  0x00000000006c4627 in ra_rematk (as=<value optimized out>, ref=<value optimized out>) at lj_asm.c:343
#7  0x00000000006ce202 in ra_evictk (J=0x413f3558, T=0x413f3558) at lj_asm.c:513
#8  lj_asm_trace (J=0x413f3558, T=0x413f3558) at lj_asm.c:2363
#9  0x000000000069faad in trace_state (L=0x463eaa60, dummy=<value optimized out>, ud=0x413f3558) at lj_trace.c:691
#10 0x00000000006a9d1a in lj_vm_cpcall () at buildvm_x86.dasc:1181
#11 0x000000000069ebed in lj_trace_ins (J=0x413f3558, pc=<value optimized out>) at lj_trace.c:723
#12 0x000000000068f275 in lj_dispatch_ins (L=0x463eaa60, pc=0x400f9bbc) at lj_dispatch.c:424
#13 0x00000000006ab315 in lj_vm_inshook () at buildvm_x86.dasc:2350
```

I'm wondering if the coredump is related with  ra_rematk().

**Comment by hongxiaolong** [comment]
@agentzh Could u please help have a look at this problem
