### ISSUE TITLE
Core dump on Raspberry Pi

### ISSUE THREAD

**Issue by irimiab** [openresty/openresty#414]
We are running FreeBSD on a **Raspberry Pi 3 model B+**: `FreeBSD k50 12.0-BETA2 FreeBSD 12.0-BETA2 r339753 GENERIC  arm64` and compiled OpenResty on it:
```
nginx version: openresty/1.13.6.2
built by clang 6.0.1 (tags/RELEASE_601/final 335540) (based on LLVM 6.0.1)
built with OpenSSL 1.1.1-freebsd  11 Sep 2018
TLS SNI support enabled
configure arguments: --prefix=/opt/kronometrix/kernel/stats/nginx --with-cc-opt=-O2 --add-module=../ngx_devel_kit-0.3.0 --add-module=../echo-nginx-module-0.61 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2rc3 --add-module=../set-misc-nginx-module-0.32 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.08 --add-module=../srcache-nginx-module-0.31 --add-module=../ngx_lua-0.10.13 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.33 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.19 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.7 --add-module=../rds-json-nginx-module-0.15 --add-module=../rds-csv-nginx-module-0.09 --add-module=../ngx_stream_lua-0.0.5 --with-ld-opt=-Wl,-rpath,/opt/kronometrix/kernel/stats/luajit/lib --with-cc=/usr/bin/cc --with-stream --with-stream_ssl_module --with-http_ssl_module
```

We are getting sporadic errors and core dumps:
- one error is related with the websocket server:
```
2018/10/31 16:02:35 [error] 3797#0: *1900 lua entry thread aborted: runtime error: ...ometrix/kernel/stats/lualib/resty/websocket/protocol.lua:0: attempt to get length of a boolean value
stack traceback:
coroutine 0:
        ...ometrix/kernel/stats/lualib/resty/websocket/protocol.lua: in function '_send_frame'
        ...onometrix/kernel/stats/lualib/resty/websocket/server.lua:167: in function 'send_close'
        /opt/kronometrix/kernel/stats/nginx/../app/websocket2.lua:179: in function 'run_websocket'
        ...metrix/kernel/stats/nginx/../app/data_display_routes.lua:489: in function 'f'
        /opt/kronometrix/kernel/stats/lualib/resty/router.lua:128: in function 'execute'
        ...metrix/kernel/stats/nginx/../app/data_display_routes.lua:492: in function <...metrix/kernel/stats/nginx/../app/data_display_routes.lua:1>, client: 127.0.0.1, server: , request: "GET /websocket HTTP/1.1", host: "192.168.2.207"
```
and this:
```
2018/11/01 15:38:10 [error] 8589#0: *3384 lua entry thread aborted: runtime error: ...ometrix/kernel/stats/lualib/resty/websocket/protocol.lua:0: attempt to index a number value
stack traceback:
coroutine 0:
        ...ometrix/kernel/stats/lualib/resty/websocket/protocol.lua: in function '_send_frame'
        ...onometrix/kernel/stats/lualib/resty/websocket/server.lua:167: in function 'send_close'
        /opt/kronometrix/kernel/stats/nginx/../app/websocket2.lua:179: in function 'run_websocket'
        ...metrix/kernel/stats/nginx/../app/data_display_routes.lua:489: in function 'f'
        /opt/kronometrix/kernel/stats/lualib/resty/router.lua:128: in function 'execute'
        ...metrix/kernel/stats/nginx/../app/data_display_routes.lua:492: in function <...metrix/kernel/stats/nginx/../app/data_display_routes.lua:1>, client: 127.0.0.1, server: , request: "GET /websocket HTTP/1.1", host: "192.168.2.207"
```
and this:
```
2018/11/01 09:49:56 [error] 1029#0: *9151 lua entry thread aborted: runtime error: ...ometrix/kernel/stats/lualib/resty/websocket/protocol.lua:0: attempt to call a nil value
stack traceback:
coroutine 0:
        ...ometrix/kernel/stats/lualib/resty/websocket/protocol.lua: in function '_send_frame'
        ...onometrix/kernel/stats/lualib/resty/websocket/server.lua:167: in function 'send_close'
        /opt/kronometrix/kernel/stats/nginx/../app/websocket2.lua:179: in function 'run_websocket'
        ...metrix/kernel/stats/nginx/../app/data_display_routes.lua:489: in function 'f'
        /opt/kronometrix/kernel/stats/lualib/resty/router.lua:128: in function 'execute'
        ...metrix/kernel/stats/nginx/../app/data_display_routes.lua:492: in function <...metrix/kernel/stats/nginx/../app/data_display_routes.lua:1>, client: 127.0.0.1, server: , request: "GET /websocket HTTP/1.1", host: "192.168.2.207"
```
- another strange behavior is that it seems a totally different Lua library is being called without being explicitly used in the code:
```
2018/11/01 10:56:02 [error] 6374#0: *10638 lua entry thread aborted: runtime error: /opt/kronometrix/kernel/stats/nginx/../app/checksums.lua:17: attempt to call method 'byte' (a nil value)
stack traceback:
coroutine 0:
        /opt/kronometrix/kernel/stats/nginx/../app/checksums.lua: in function 'send_close'
        /opt/kronometrix/kernel/stats/nginx/../app/websocket2.lua:179: in function 'run_websocket'
        ...metrix/kernel/stats/nginx/../app/data_display_routes.lua:489: in function 'f'
        /opt/kronometrix/kernel/stats/lualib/resty/router.lua:128: in function 'execute'
        ...metrix/kernel/stats/nginx/../app/data_display_routes.lua:492: in function <...metrix/kernel/stats/nginx/../app/data_display_routes.lua:1>, client: 127.0.0.1, server: , request: "GET /websocket HTTP/1.1", host: "192.168.2.207"
```
In the case above, the library `checksums.lua` is not included anywhere in `websocket2.lua` or in any place related with the websocket.
- we are also getting core dumps pretty often; here are some details from the core dump:
```
GNU gdb (GDB) 8.2 [GDB v8.2 for FreeBSD]
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "aarch64-portbld-freebsd12.0".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /opt/kronometrix/kernel/stats/nginx/sbin/nginx...done.
[New LWP 100144]
Core was generated by `nginx: worker process'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000001d054c in ?? ()
(gdb) backtrace
#0  0x00000000001d054c in ?? ()
#1  0x0000ffffffffe4a0 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb) info registers
x0             0x4151e460          1095885920
x1             0xfffeffffffffffff  -281474976710657
x2             0xfff90000          4294508544
x3             0xfffd800043251c80  -703686315271040
x4             0x4315707d          1125478525
x5             0x439cd027          1134350375
x6             0x697463656e6e6f63  7598807758576447331
x7             0x206c6c6977206e6f  2336361506924424815
x8             0x359e34            3513908
x9             0x6                 6
x10            0xfffffffffffffffb  -5
x11            0x432584f8          1126532344
x12            0x434359c0          1128487360
x13            0x20000000          536870912
x14            0x2065736f          543519599
x15            0xfffffffffffffff7  -9
x16            0xad0e5b            11341403
x17            0x43900670          1133512304
x18            0x0                 0
x19            0x439006a8          1133512360
x20            0x4325b328          1126544168
x21            0x415227d0          1095903184
x22            0x4151e3d8          1095885784
x23            0x4382ce38          1132645944
x24            0xfff9000000000000  -1970324836974592
x25            0x434359a8          1128487336
x26            0x8                 8
x27            0x63ff9c            6553500
x28            0x17                23
x29            0xffffffffe340      281474976703296
x30            0xc997d4            13211604
sp             0xffffffffe330      0xffffffffe330
pc             0x1d054c            0x1d054c
cpsr           0x20000000          [ EL=0 C ]
fpsr           0x11                17
fpcr           0x0                 0
(gdb) x/16i $pc
=> 0x1d054c:    ldr     x30, [x26, #8]
   0x1d0550:    cmp     x0, x30
   0x1d0554:    b.eq    0x1d06c4  // b.none
   0x1d0558:    ldr     x26, [x26, #16]
   0x1d055c:    cmp     x26, #0x0
   0x1d0560:    b.ne    0x1d054c  // b.any
   0x1d0564:    ldr     x26, [x27, #32]
   0x1d0568:    cbz     x26, 0x1d06c4
   0x1d056c:    ldr     w21, [x26, #52]
   0x1d0570:    cmp     w21, #0x1
   0x1d0574:    b.ne    0x1d06c4  // b.any
   0x1d0578:    ldr     x17, [x26, #40]
   0x1d057c:    ldr     x26, [x17, #32]
   0x1d0580:    cmp     x26, x1
   0x1d0584:    b.ne    0x1d06c4  // b.any
   0x1d0588:    ldr     x26, [x17, #24]
```

Further info about NginX:
```
# ldd sbin/nginx
sbin/nginx:
        libcrypt.so.5 => /lib/libcrypt.so.5 (0x40441000)
        libm.so.5 => /lib/libm.so.5 (0x40493000)
        libdl.so.1 => /usr/lib/libdl.so.1 (0x40504000)
        libpcre.so.1 => /usr/local/lib/libpcre.so.1 (0x40535000)
        libssl.so.111 => /usr/lib/libssl.so.111 (0x405e6000)
        libcrypto.so.111 => /lib/libcrypto.so.111 (0x40687000)
        libz.so.6 => /lib/libz.so.6 (0x4090a000)
        libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x4093b000)
        libc.so.7 => /lib/libc.so.7 (0x4097c000)
        libthr.so.3 => /lib/libthr.so.3 (0x40d53000)
# pkg-static info pcre
pcre-8.42
Name           : pcre
Version        : 8.42
Installed on   : Wed Oct 31 04:00:54 2018 UTC
Origin         : devel/pcre
Architecture   : FreeBSD:12:aarch64
Prefix         : /usr/local
Categories     : devel
Licenses       : BSD3CLAUSE
Maintainer     : krion@FreeBSD.org
WWW            : https://www.pcre.org/
Comment        : Perl Compatible Regular Expressions library
Options        :
        DOCS           : on
        LIBEDIT        : off
        MAN3           : on
        READLINE       : off
        STACK_RECURSION: on
Shared Libs provided:
        libpcre32.so.0
        libpcre.so.1
        libpcreposix.so.0
        libpcrecpp.so.0
        libpcre16.so.0
Annotations    :
        FreeBSD_version: 1200084
        cpe            : cpe:2.3:a:pcre:pcre:8.42:::::freebsd12:aarch64
        repo_type      : binary
        repository     : FreeBSD
Flat size      : 6.76MiB
Description    :
The PCRE library is a set of functions that implement regular expression
pattern matching using the same syntax and semantics as Perl 5. PCRE has its
own native API, as well as a set of wrapper functions that correspond to the
POSIX regular expression API. The PCRE library is free, even for building
proprietary software.

WWW: https://www.pcre.org/
```

**Comment by agentzh** [comment]
@irimiab OpenResty 1.13.6.2 (and any earlier versions) do not really support the arm64 architecture. The support for arm64 was just recently added. Please try the following preview version instead:

https://openresty.org/download/openresty-1.15.5.1rc0.tar.gz

**Comment by agentzh** [comment]
@irimiab Make sure you are using OpenResty's own components instead of your own, like LuaJIT, lua-cjson, lua-resty-websocket, and etc. Some 3rd-party Lua C modules using light userdata is very likely to have compatibility issues on arm64; you should either avoid them or patch them in a similar way we patch lua-cjson.

**Comment by sparvu** [comment]
Cheers. We will try the 1.15.5.1 release and report back. We should use only core OpenResty modules. 
But one big difference was using on FreeBSD 12 the stable OpenSSL 1.1.1

But somehow building OpenResty against openssl 1.1.1 was just fine. No problems.

**Comment by sparvu** [comment]
@agentzh: thanks. no more crashes.
