### ISSUE TITLE
segfault in ngx_stream_lua_req_socket_rev_handler

### ISSUE THREAD

**Issue by tfsdev** [openresty/openresty#585]
When running the attached server and client code on openresty 1.15.8.2, I can observe frequently nginx process segfault.

I understand the segfault is caused by incorrect lua code behavior (share socket handle via global variable), but I  believe openresty should gracefully report a runtime error instead of crash nginx process.

[crash.zip](https://github.com/openresty/openresty/files/4191508/crash.zip)

typical crash stack is like:

```
#0  ngx_stream_lua_req_socket_rev_handler (r=0x558f3c839280) at ../ngx_stream_lua-0.0.7/src/ngx_stream_lua_socket_tcp.c:4629
#1  0x0000558f3b818cd4 in ngx_epoll_process_events (cycle=<optimized out>, timer=<optimized out>, flags=<optimized out>)
    at src/event/modules/ngx_epoll_module.c:902
#2  0x0000558f3b80fd2c in ngx_process_events_and_timers (cycle=cycle@entry=0x558f3c7bf0a0) at src/event/ngx_event.c:252
#3  0x0000558f3b816ca8 in ngx_worker_process_cycle (cycle=cycle@entry=0x558f3c7bf0a0, data=data@entry=0x0) at src/os/unix/ngx_process_cycle.c:816
#4  0x0000558f3b815588 in ngx_spawn_process (cycle=cycle@entry=0x558f3c7bf0a0, proc=proc@entry=0x558f3b816c30 <ngx_worker_process_cycle>, 
    data=data@entry=0x0, name=name@entry=0x558f3b90c9cd "worker process", respawn=respawn@entry=-3) at src/os/unix/ngx_process.c:199
#5  0x0000558f3b817150 in ngx_start_worker_processes (cycle=cycle@entry=0x558f3c7bf0a0, n=2, type=type@entry=-3) at src/os/unix/ngx_process_cycle.c:397
#6  0x0000558f3b817ada in ngx_master_process_cycle (cycle=0x558f3c7bf0a0) at src/os/unix/ngx_process_cycle.c:136
#7  0x0000558f3b7efe9a in main (argc=<optimized out>, argv=<optimized out>) at src/core/nginx.c:382
```

**Comment by agentzh** [comment]
@tfsdev Will you provide a minimal example that we can easily reproduce the crash? Thanks!

Also, it'll be great if you can try our 1.17.8.1 RC0 preview version on your side if it's still reproducible with the latest version of the code:

https://openresty.org/download/openresty-1.17.8.1rc0.tar.gz

**Comment by tfsdev** [comment]
Yes I can reproduce the same problem on 1.17.8.1rc0.
All you need to reproduce the problem is in the attached zip file in my bug report.
