### ISSUE TITLE
使用openrest，但是在请求的第三方接口超时的时候nginx进程无响应

### ISSUE THREAD

**Issue by fanxinglb** [openresty/openresty#74]
为啥我们用的nginx lua，有时候后端请求的接口超时，会导致nginx进程僵死，占用大量cpu，一直不响应，可能是什么原因？
用pstack 进程看返回如下：
#0  0x00007f12ebc77191 in lua_pushcclosure () from /usr/local/lib/libluajit-5.1.so.2
#1  0x00000000004c7d53 in ngx_http_lua_socket_tcp_receiveuntil ()
#2  0x00007f12ebc6ae0b in ?? () from /usr/local/lib/libluajit-5.1.so.2
#3  0x00000000004bcdd0 in ngx_http_lua_run_thread ()
#4  0x00000000004c4d38 in ngx_http_lua_socket_tcp_resume_helper ()
#5  0x00000000004c67bd in ngx_http_lua_socket_tcp_read ()
#6  0x00000000004c4c6a in ngx_http_lua_socket_tcp_handler ()
#7  0x000000000043ab0f in ngx_epoll_process_events ()
#8  0x0000000000432b69 in ngx_process_events_and_timers ()
#9  0x0000000000438dd8 in ngx_worker_process_cycle ()
#10 0x0000000000437307 in ngx_spawn_process ()
#11 0x00000000004381cc in ngx_start_worker_processes ()
#12 0x00000000004395dc in ngx_master_process_cycle ()
#13 0x000000000041b186 in main ()

[root@cdn ~]# pstack 6040
#0  0x00007f12ebc6a69c in ?? () from /usr/local/lib/libluajit-5.1.so.2
#1  0x00000000004bcdd0 in ngx_http_lua_run_thread ()
#2  0x00000000004c4d38 in ngx_http_lua_socket_tcp_resume_helper ()
#3  0x00000000004c67bd in ngx_http_lua_socket_tcp_read ()
#4  0x00000000004c4c6a in ngx_http_lua_socket_tcp_handler ()
#5  0x000000000043ab0f in ngx_epoll_process_events ()
#6  0x0000000000432b69 in ngx_process_events_and_timers ()
#7  0x0000000000438dd8 in ngx_worker_process_cycle ()
#8  0x0000000000437307 in ngx_spawn_process ()
#9  0x00000000004381cc in ngx_start_worker_processes ()
#10 0x00000000004395dc in ngx_master_process_cycle ()
#11 0x000000000041b186 in main ()

[root@cdn ~]# pstack 6040
#0  0x00007f12ebc6f4aa in ?? () from /usr/local/lib/libluajit-5.1.so.2
#1  0x00007f12ebc703bc in ?? () from /usr/local/lib/libluajit-5.1.so.2
#2  0x00007f12ebc7772b in lua_rawget () from /usr/local/lib/libluajit-5.1.so.2
#3  0x00000000004c7be8 in ngx_http_lua_socket_tcp_receiveuntil ()
#4  0x00007f12ebc6ae0b in ?? () from /usr/local/lib/libluajit-5.1.so.2
#5  0x00000000004bcdd0 in ngx_http_lua_run_thread ()
#6  0x00000000004c4d38 in ngx_http_lua_socket_tcp_resume_helper ()
#7  0x00000000004c67bd in ngx_http_lua_socket_tcp_read ()
#8  0x00000000004c4c6a in ngx_http_lua_socket_tcp_handler ()
#9  0x000000000043ab0f in ngx_epoll_process_events ()
#10 0x0000000000432b69 in ngx_process_events_and_timers ()
#11 0x0000000000438dd8 in ngx_worker_process_cycle ()
#12 0x0000000000437307 in ngx_spawn_process ()
#13 0x00000000004381cc in ngx_start_worker_processes ()
#14 0x00000000004395dc in ngx_master_process_cycle ()
#15 0x000000000041b186 in main ()

[root@cdn ~]# pstack 6040
#0  0x00007f12ebc6a697 in ?? () from /usr/local/lib/libluajit-5.1.so.2
#1  0x00000000004bcdd0 in ngx_http_lua_run_thread ()
#2  0x00000000004c4d38 in ngx_http_lua_socket_tcp_resume_helper ()
#3  0x00000000004c67bd in ngx_http_lua_socket_tcp_read ()
#4  0x00000000004c4c6a in ngx_http_lua_socket_tcp_handler ()
#5  0x000000000043ab0f in ngx_epoll_process_events ()
#6  0x0000000000432b69 in ngx_process_events_and_timers ()
#7  0x0000000000438dd8 in ngx_worker_process_cycle ()
#8  0x0000000000437307 in ngx_spawn_process ()
#9  0x00000000004381cc in ngx_start_worker_processes ()
#10 0x00000000004395dc in ngx_master_process_cycle ()
#11 0x000000000041b186 in main ()

[root@cdn ~]# pstack 6040
#0  0x00007f12ebc7265e in ?? () from /usr/local/lib/libluajit-5.1.so.2
#1  0x00007f12ebc77790 in lua_getfield () from /usr/local/lib/libluajit-5.1.so.2
#2  0x00000000004c7a7f in ngx_http_lua_socket_tcp_receiveuntil ()
#3  0x00007f12ebc6ae0b in ?? () from /usr/local/lib/libluajit-5.1.so.2
#4  0x00000000004bcdd0 in ngx_http_lua_run_thread ()
#5  0x00000000004c4d38 in ngx_http_lua_socket_tcp_resume_helper ()
#6  0x00000000004c67bd in ngx_http_lua_socket_tcp_read ()
#7  0x00000000004c4c6a in ngx_http_lua_socket_tcp_handler ()
#8  0x000000000043ab0f in ngx_epoll_process_events ()
#9  0x0000000000432b69 in ngx_process_events_and_timers ()
#10 0x0000000000438dd8 in ngx_worker_process_cycle ()
#11 0x0000000000437307 in ngx_spawn_process ()
#12 0x00000000004381cc in ngx_start_worker_processes ()
#13 0x00000000004395dc in ngx_master_process_cycle ()
#14 0x000000000041b186 in main ()

[root@cdn ~]# pstack 6040
#0  0x00007f12ebc6cfff in ?? () from /usr/local/lib/libluajit-5.1.so.2
#1  0x00007f12ebc6de72 in ?? () from /usr/local/lib/libluajit-5.1.so.2
#2  0x00007f12ebc6e328 in ?? () from /usr/local/lib/libluajit-5.1.so.2
#3  0x00007f12ebc7720d in lua_pushcclosure () from /usr/local/lib/libluajit-5.1.so.2
#4  0x00000000004c7d53 in ngx_http_lua_socket_tcp_receiveuntil ()
#5  0x00007f12ebc6ae0b in ?? () from /usr/local/lib/libluajit-5.1.so.2
#6  0x00000000004bcdd0 in ngx_http_lua_run_thread ()
#7  0x00000000004c4d38 in ngx_http_lua_socket_tcp_resume_helper ()
#8  0x00000000004c67bd in ngx_http_lua_socket_tcp_read ()
#9  0x00000000004c4c6a in ngx_http_lua_socket_tcp_handler ()
#10 0x000000000043ab0f in ngx_epoll_process_events ()
#11 0x0000000000432b69 in ngx_process_events_and_timers ()
#12 0x0000000000438dd8 in ngx_worker_process_cycle ()
#13 0x0000000000437307 in ngx_spawn_process ()
#14 0x00000000004381cc in ngx_start_worker_processes ()
#15 0x00000000004395dc in ngx_master_process_cycle ()
#16 0x000000000041b186 in main ()

[root@cdn ~]# pstack 6040
#0  0x00007f12ebc760d8 in ?? () from /usr/local/lib/libluajit-5.1.so.2
#1  0x00007f12ebc776a0 in lua_rawgeti () from /usr/local/lib/libluajit-5.1.so.2
#2  0x00000000004c988f in ngx_http_lua_socket_receiveuntil_iterator ()
#3  0x00007f12ebc6ae0b in ?? () from /usr/local/lib/libluajit-5.1.so.2
#4  0x00000000004bcdd0 in ngx_http_lua_run_thread ()
#5  0x00000000004c4d38 in ngx_http_lua_socket_tcp_resume_helper ()
#6  0x00000000004c67bd in ngx_http_lua_socket_tcp_read ()
#7  0x00000000004c4c6a in ngx_http_lua_socket_tcp_handler ()
#8  0x000000000043ab0f in ngx_epoll_process_events ()
#9  0x0000000000432b69 in ngx_process_events_and_timers ()
#10 0x0000000000438dd8 in ngx_worker_process_cycle ()
#11 0x0000000000437307 in ngx_spawn_process ()
#12 0x00000000004381cc in ngx_start_worker_processes ()
#13 0x00000000004395dc in ngx_master_process_cycle ()
#14 0x000000000041b186 in main ()

**Comment by zhuizhuhaomeng** [comment]
close old issue.
