### ISSUE TITLE
core dump by lua ffi.string

### ISSUE THREAD

**Issue by djunny** [openresty/openresty#822]
os
```
docker from alpine3.14
```

openresty version 

```
nginx version: openresty/1.19.9.1
built by gcc 10.3.1 20210424 (Alpine 10.3.1_git20210424) 
built with OpenSSL 1.1.1l  24 Aug 2021
TLS SNI support enabled
configure arguments: --prefix=/opt/openresty/nginx --with-cc-opt=-O2 --add-module=../ngx_devel_kit-0.3.1 --add-module=../echo-nginx-module-0.62 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2 --add-module=../set-misc-nginx-module-0.32 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.08 --add-module=../srcache-nginx-module-0.32 --add-module=../ngx_lua-0.10.20 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.33 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.19 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.7 --add-module=../rds-json-nginx-module-0.15 --add-module=../rds-csv-nginx-module-0.09 --add-module=../ngx_stream_lua-0.0.10 --with-ld-opt=-Wl,-rpath,/opt/openresty/luajit/lib --with-http_ssl_module --with-pcre-jit --with-stream --with-stream_ssl_module --with-http_v2_module --with-http_gzip_static_module --add-module=/usr/src/ngx_brotli --with-stream --with-stream_ssl_preread_module
```

core dump:

```
#0  0x00007f670f97280b in strlen () from /lib/ld-musl-x86_64.so.1
(gdb) bt
#0  0x00007f670f97280b in strlen () at /lib/ld-musl-x86_64.so.1
#1  0x00007f670f904ffb in lj_cf_ffi_string (L=0x7f667e765380) at lib_ffi.c:691
#2  0x00007f670f8a7b6a in lj_BC_FUNCC () at /opt/openresty/luajit/lib/libluajit-5.1.so.2
#3  0x00007f670f8ba82f in lua_pcall (L=L@entry=0x7f667e765380, nargs=nargs@entry=0, nresults=nresults@entry=1, errfunc=errfunc@entry=1) at lj_api.c:1140
#4  0x0000558f50f2877c in ngx_http_lua_body_filter_by_chunk (L=L@entry=0x7f667e765380, r=r@entry=0x7f667e11d0e0, in=in@entry=0x7ffcdd6f8e90)
    at ../ngx_lua-0.10.20/src/ngx_http_lua_bodyfilterby.c:104
#5  0x0000558f50f289d3 in ngx_http_lua_body_filter_file (r=0x7f667e11d0e0, in=0x7ffcdd6f8e90) at ../ngx_lua-0.10.20/src/ngx_http_lua_bodyfilterby.c:219
#6  0x0000558f50f28405 in ngx_http_lua_body_filter (r=0x7f667e11d0e0, in=0x7ffcdd6f8e90) at ../ngx_lua-0.10.20/src/ngx_http_lua_bodyfilterby.c:290
#7  0x0000558f50ead43f in ngx_http_copy_filter (r=0x7f667e11d0e0, in=0x7ffcdd6f8e90) at src/http/ngx_http_copy_filter_module.c:152
#8  0x0000558f50e7e70b in ngx_http_output_filter (r=r@entry=0x7f667e11d0e0, in=in@entry=0x7ffcdd6f8e90) at src/http/ngx_http_core_module.c:1861
#9  0x0000558f50e81fb0 in ngx_http_send_special (r=r@entry=0x7f667e11d0e0, flags=flags@entry=1) at src/http/ngx_http_request.c:3559
#10 0x0000558f50e9377d in ngx_http_upstream_finalize_request (r=0x7f667e11d0e0, u=0x7f667e121c68, rc=<optimized out>) at src/http/ngx_http_upstream.c:4515
#11 0x0000558f50e93822 in ngx_http_upstream_handler (ev=<optimized out>) at src/http/ngx_http_upstream.c:1301
#12 0x0000558f50e6c2d8 in ngx_epoll_process_events (cycle=<optimized out>, timer=<optimized out>, flags=<optimized out>)
    at src/event/modules/ngx_epoll_module.c:901
#13 0x0000558f50e62ba4 in ngx_process_events_and_timers (cycle=cycle@entry=0x7f670f2aa290) at src/event/ngx_event.c:257
#14 0x0000558f50e6a258 in ngx_worker_process_cycle (cycle=cycle@entry=0x7f670f2aa290, data=data@entry=0x1) at src/os/unix/ngx_process_cycle.c:782
#15 0x0000558f50e689e9 in ngx_spawn_process
    (cycle=cycle@entry=0x7f670f2aa290, proc=proc@entry=0x558f50e6a1e0 <ngx_worker_process_cycle>, data=data@entry=0x1, name=name@entry=0x558f50fb5773 "worker process", respawn=respawn@entry=-4) at src/os/unix/ngx_process.c:199
#16 0x0000558f50e697dc in ngx_start_worker_processes (cycle=cycle@entry=0x7f670f2aa290, n=8, type=type@entry=-4) at src/os/unix/ngx_process_cycle.c:382
#17 0x0000558f50e6adf6 in ngx_master_process_cycle (cycle=0x7f670f2aa290) at src/os/unix/ngx_process_cycle.c:241
#18 0x0000558f50e41b9d in main (argc=<optimized out>, argv=<optimized out>) at src/core/nginx.c:386
```

body_filter_by_lua_file:

```

local ffi_str = ffi.string

local function convert_method(input)
   -- there is some c method call
   -- CRASH in ffi_str
   local string_result, output_str = pcall(ffi_str, output)
   return convert_method
end

local chunk, eof = ngx.arg[1], ngx.arg[2]
chunk = chunk or ""

local buffered = ngx.ctx.buffered
if not buffered then
    buffered = {}
    ngx.ctx.buffered = buffered
end

if eof then
    local whole = table.concat(buffered)
    ngx.ctx.buffered = nil
    ngx.arg[1] = convert_method(whole or "")
elseif chunk ~= "" then
    buffered[#buffered + 1] = chunk
    ngx.arg[1] = nil
end

```

It's not necessarily core dump every time

so we can't find a specific reason

But the convert_method converts the some CJK content

**Comment by zhuizhuhaomeng** [comment]
https://riptutorial.com/lua/example/16000/using-pcall

local output = pcall(opencc.opencc_convert_utf8, instance, input, #input)
the output is true/false, not the value expected
should be

local ok, output = pcall(opencc.opencc_convert_utf8, instance, input, #input)

**Comment by djunny** [comment]
sorry, it‘s my mistake to write minimal code for test .

But this crash is not because of this pcall…

**Comment by zhuizhuhaomeng** [comment]
the gdb shows that the output is a NULLL pointer, but you have test output ==nil.
I have no idea why the code still runs to the ffi.string.
